intro/urls.py
from django.contrib import admin
from django.urls import path, include


from hello import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', views.hello),
    path('name/', views.name),
    path('hi/', views.hi),
    path('hi2/', views.hi2),

    path('next/', include('next_app.urls')),
    path('links/', include('links.urls')),
    path('inheritance/', include('inheritance.urls')),
    path('form/', include('form_app.urls')),
    path('form2/', include('form_app2.urls')),
    path('form3/', include('form_app3.urls')),
    path('form4/', include('form_app4.urls')),
    path('form5/', include('form_app5.urls')),
    path('crud_app/', include('crud_app.urls')),
    path('relations/', include('relations_app.urls')),
]

links/urls.py
from django.urls import path

from links import views

app_name = 'links'

urlpatterns = [
    path('first/', views.first_view, name='first_name'),
    path('second/', views.second_view, name='second_name'),
    path('third/<str:param>/', views.third_view, name='third_name'),
]

links/views.py
from django.shortcuts import render


# Create your views here.
def first_view(request):
    return render(
        request,
        'first_template.html',
    )


def second_view(request):
    return render(
        request,
        'second_template.html',
    )


def third_view(request, param):
    return render(
        request,
        'third_template.html',
        context={
            'param': param,
        }
    )

links/templates/links/first_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1> TO jest pierwsza strona</h1>
Lorem
<p> Przejdź do strony <a href="{% url 'links:second_name' %}">drugiej</a></p>
</body>
</html>

links/templates/links/second_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1> TO jest druga strona</h1>
Lorem
<p> Przejdź do strony <a href="{% url 'links:third_name' 'abc' %}">trzeciej</a></p>

</body>
</html>

links/templates/links/third_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <h1>To jest trzecia strona z parametrem {{ param }}</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid aut blanditiis dicta eius exercitationem fugit, ipsum laboriosam minima minus modi, molestias nihil nisi omnis quae recusandae repudiandae, veniam vero voluptate?</p>

  <p>Przejdź do strony <a href="{% url 'links:first_name' %}">pierwszej</a></p>
</body>
</html>